version: '3.8'

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: nord-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
      - pma
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: nord-php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
    # image: mysql:8.0 macOS m1 netinka
    image: arm64v8/mysql:latest
    container_name: nord-mysql
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
    ports:
      - 33060:3306
  pma:
    image: phpmyadmin
    container_name: nord-pma
    restart: unless-stopped
    env_file:
      - ./env/pma.env
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 88:80
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    container_name: nord-composer
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: nord-artisan
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:latest
    container_name: nord-npm
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html